name: qurany_karim
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  dartz: ^0.10.1
  provider: ^6.0.2
  after_layout: ^1.1.0
  shared_preferences: ^2.0.13
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  pull_to_refresh: ^2.0.0
  localize_and_translate: ^4.1.1
  share_plus: ^4.0.4
  geolocator: ^7.7.1
  flutter_qiblah: ^2.0.2
  adhan: ^2.0.0-nullsafety.2
  intl: ^0.17.0
  animate_do: ^2.1.0
  assets_audio_player: ^3.0.4+1
  youtube_player_flutter: ^8.0.0
  package_info: ^2.0.2
  url_launcher: ^6.0.20
  store_redirect: ^2.0.1
  fluttertoast: ^8.0.9
  flutter_screenutil: ^5.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  hive_generator: ^1.1.2
  build_runner: ^2.1.10
  flutter_native_splash: ^2.1.5
flutter_native_splash:
  color: "#6C3483"
  image: "assets/icons/drawer_logo.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/langs/ar.json
    - assets/langs/en.json
    - assets/images/
    - assets/icons/
    - assets/json_db/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: ReemKufi
      fonts:
        - asset: assets/fonts/ReemKufi-Regular.ttf

