name: qurany_karim
description: A new Flutter project.

publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  dio: ^4.0.6
  dartz: ^0.10.1
  provider: ^6.1.1
  after_layout: ^1.2.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pull_to_refresh: ^2.0.0
  localize_and_translate: ^4.1.1
  share_plus: ^7.2.1
  geolocator: ^9.0.2
  flutter_qiblah: ^2.2.0
  adhan: ^2.0.0+1
  intl: ^0.18.1
  animate_do: ^3.1.2
  assets_audio_player: ^3.1.1
  youtube_player_flutter: ^8.1.2
  package_info: ^2.0.2
  url_launcher: ^6.2.1
  store_redirect: ^2.0.1
  fluttertoast: ^8.2.4
  flutter_screenutil: ^5.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_native_splash: ^2.3.6
flutter_native_splash:
  color: "#6C3483"
  image: "assets/icons/drawer_logo.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/langs/ar.json
    - assets/langs/en.json
    - assets/images/
    - assets/icons/
    - assets/json_db/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: ReemKufi
      fonts:
        - asset: assets/fonts/ReemKufi-Regular.ttf

